
name: Build and Deploy to Staging CDNs
on:
  release:
    types: [published]
env:
  BUCKET_NAME : "cdn.annoto.net"
  AWS_REGION : "eu-central-1"
  CLOUDFRONT_DIST_ID: "E2PYBK8LLNZMVK"
  REPO_NAME: ${{ github.event.repository.name }}
  APP_VERSION: ${{ github.ref_name }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install Packages
      run: npm ci
    - name: Build
      run: npm run build:staging
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::281726344480:role/nn-cdn-deploy-${{ env.REPO_NAME }}
        role-session-name: deploy-${{ env.REPO_NAME }}-${{ env.APP_VERSION }}-${{ github.actor }}
    - name: Sync to S3 latest
      run: |
        aws s3 sync ./dist \
        "s3://${{ env.BUCKET_NAME }}/staging/${{ env.REPO_NAME }}/latest/" \
        --cache-control "no-cache,no-transform,max-age=86400" \
        --delete
    - name: Invalidate Cloudfront
      run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ env.CLOUDFRONT_DIST_ID }} \
        --paths "/staging/${{ env.REPO_NAME }}/latest*"
    